### ISSUE TITLE
Autoloading not working

### ISSUE THREAD

**Issue by andrejs-uibo** [cardpay/php-sdk#2]
When trying to use your SDK from vendors, it is not autoloaded by composer.
Probably need to add this to composer.json:
`"autoload": {
            "psr-4": {
                "CardPay\\": "lib/CardPay"
            }
        },`

**Comment by andrejs-uibo** [comment]
Still not fixed.
Now it has:
` "CardPay\\": "lib/"`
but to work correctly, it needs to be: 
` "CardPay\\": "lib/CardPay"`

**Comment by evpanov** [comment]
fixed
